name: asf-jupyter-notebook
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.1.1
  - numpy=1.19.1
  - matplotlib=3.3.2
  - gdal=3.1.3
  - pandas=1.1.3
  - rasterio=1.1.7
  - scikit-fuzzy=0.4.2
  - pyproj=2.6.1.post1
  - pip:
      - awscli==1.18.156
